### ISSUE TITLE
SSMS 18.1 extension V1.6.13 does not load 'The 'FormatterPackage' package did not load correctly.' - Assembly Version Mismatches

### ISSUE THREAD

**Issue by CZEMacLeod** [TaoK/PoorMansTSqlFormatter#227]
After installing V1.6.13 and opening SSMS 18.1 I get the following error:
```
---------------------------
Microsoft SQL Server Management Studio
---------------------------
The 'FormatterPackage' package did not load correctly.

The problem may have been caused by a configuration change or by the installation of another extension. You can get more information by examining the file 'C:\Users\xxxx\AppData\Roaming\Microsoft\AppEnv\15.0\ActivityLog.xml'.

Restarting Visual Studio could help resolve this issue.

Continue to show this error message?
---------------------------
Yes   No   
---------------------------
```
Checking that file I see the following:
```
LegacySitePackage failed for package [FormatterPackage]Source: 'PoorMansTSqlFormatterSSMSLib' Description: 
Could not load file or assembly 'PoorMansTSqlFormatterPluginShared, Version=1.6.12.2816, Culture=neutral, PublicKeyToken=fb9a6042fd921db9' or one of its dependencies. 
The system cannot find the file specified. System.IO.FileNotFoundException: 
Could not load file or assembly 'PoorMansTSqlFormatterPluginShared, Version=1.6.12.2816, Culture=neutral, PublicKeyToken=fb9a6042fd921db9' or one of its dependencies. 
The system cannot find the file specified. 
File name: 'PoorMansTSqlFormatterPluginShared, Version=1.6.12.2816, Culture=neutral, PublicKeyToken=fb9a6042fd921db9'at PoorMansTSqlFormatterSSMSLib.GenericVSHelper..ctor(Boolean isVisualStudio, GetTextEditorKeyBindingScopeName keyBindingScopeNameDelegate, GetKeyBinding getKeyBindingDelegate, SetKeyBinding setKeyBindingDelegate)at PoorMansTSqlFormatterSSMSPackage.FormatterPackage.Initialize()at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp) 
WRN: Assembly binding logging is turned OFF. 
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1. 
Note: There is some performance penalty associated with assembly bind failure logging. 
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog]. 
```
Doing a quick check of the assemblies included in the .msi installer PoorMansTSqlFormatterSSMSLib.dll seems to be built as V1.6.12 and linked against V1.6.12 as described above, but the included DLLs are V1.6.13.
Guessing PoorMansTSqlFormatterSSMSLib needs to be rebuilt and the msi package updated.

**Comment by RichardDavies** [comment]
I'm also experiencing this same issue on a fresh install of SSMS 18.2.

**Comment by mreyeros** [comment]
Same issue for me on SSMS 18.1

**Comment by TaoK** [comment]
Thanks for the prompt and comprehensive issue report, the installer is fixed, and available for download (on architechshack.com and github) as 1.6.13b.

**Comment by RichardDavies** [comment]
I've uninstalled it and installed 1.6.13b but I'm still getting the same error.

**Comment by TaoK** [comment]
@RichardDavies: could you check the activity log file as @CZEMacLeod did above, and confirm whether they detailed message also still looks the same, please?

The new package did work for me, and **so far** no-one else seems to have any issues with it...

**Comment by RichardDavies** [comment]
Here's what my log says:

```CreateInstance failed for package [FormatterPackage]Source: 'mscorlib' Description: Could not load file or assembly 'Microsoft.VisualStudio.Shell.12.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. 

The system cannot find the file specified. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Shell.12.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. 

The system cannot find the file specified. File name: 'Microsoft.VisualStudio.Shell.12.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'   
at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)   
at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)   
at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)   
at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName) 

WRN: Assembly binding logging is turned OFF. To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1. 

Note: There is some performance penalty associated with assembly bind failure logging. To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].```

**Comment by Lukas31781** [comment]
HI,

I have the same problem, I have installed only SSMS 18.2 and tool 1.6.13b, Windows 10 1803


> 
<description>CreateInstance failed for package [FormatterPackage]Source: &apos;mscorlib&apos; Description: Nie mo&#x017C;na za&#x0142;adowa&#x0107; pliku lub zestawu &apos;Microsoft.VisualStudio.Shell.12.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; lub jednej z jego zale&#x017C;no&#x015B;ci. Nie mo&#x017C;na odnale&#x017A;&#x0107; okre&#x015B;lonego pliku.&#x000D;&#x000A;System.IO.FileNotFoundException: Nie mo&#x017C;na za&#x0142;adowa&#x0107; pliku lub zestawu &apos;Microsoft.VisualStudio.Shell.12.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; lub jednej z jego zale&#x017C;no&#x015B;ci. Nie mo&#x017C;na odnale&#x017A;&#x0107; okre&#x015B;lonego pliku.&#x000D;&#x000A;File name: &apos;Microsoft.VisualStudio.Shell.12.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)&#x000D;&#x000A;   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)&#x000D;&#x000A;   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)&#x000D;&#x000A;&#x000D;&#x000A;OSTRZE&#x017B;ENIE: rejestrowanie informacji o powi&#x0105;zaniach zestaw&#x00F3;w jest wy&#x0142;&#x0105;czone.&#x000D;&#x000A;Aby w&#x0142;&#x0105;czy&#x0107; rejestrowanie b&#x0142;&#x0119;d&#x00F3;w powi&#x0105;za&#x0144; zestaw&#x00F3;w, ustaw warto&#x015B;&#x0107; rejestru [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) r&#x00F3;wn&#x0105; 1.&#x000D;&#x000A;Uwaga: z w&#x0142;&#x0105;czeniem rejestrowania b&#x0142;&#x0119;d&#x00F3;w powi&#x0105;za&#x0144; zestaw&#x00F3;w wi&#x0105;&#x017C;e si&#x0119; pewien spadek wydajno&#x015B;ci.&#x000D;&#x000A;Aby wy&#x0142;&#x0105;czy&#x0107; t&#x0119; funkcj&#x0119;, usu&#x0144; warto&#x015B;&#x0107; rejestru [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
    <guid>{247609B1-2692-47D6-972A-976544685F0E}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo></errorinfo>
>

**Comment by TaoK** [comment]
I've opened issue #234 for this new issue @RichardDavies and @Lukas31781. Closing this one now.

**Comment by srinivaspillalamarri** [comment]
SSMS 18.1 extension 15.0 showing inactive menu
